name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - *

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use Node.js 16.x

      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Changing Directory
        run: cd nepalingo-web
        
      - name: Install dependencies
        run: pnpm install

      - name: Lint code
        run: pnpm run lint