name: Tests

on:
  push:
    branches:
      - '*'
jobs:
  test_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        #Got this from the official docs
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Changed version to v20
          cache: 'pnpm'
        
      - name: Install dependencies
        run: pnpm -C nepalingo-web install

      - name: Lint code
        run: pnpm -C nepalingo-web run lint 

      - name: Test Build
        run: pnpm -C nepalingo-web run build 
