name: Tests

on:
  push:
    branches:
      - '*'
jobs:
  test_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use Node.js 18.x 

      - name: Changing Directory
        run: cd nepalingo-web

      - name: Install pnpm
        run: npm install -g pnpm
        
      - name: Install dependencies
        run: pnpm  install

      - name: Lint code
        run: pnpm run lint 

      - name: Test Build
        run: pnpm run build 
